spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS:true}
            required: ${MAIL_STARTTLS:true}

yomora:
  mail:
    from: ${MAIL_FROM}
    password-reset-deep-link: ${PASSWORD_RESET_DEEP_LINK:yomora://password-reset?token=}
